name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20
        
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Build for Linux (x64)
      run: go build -o gomcbe-linux-x64 cmd/gomcbe/main.go
      env:
        GOOS: linux
        GOARCH: amd64
    
    - name: Build for Linux (x86)
      run: go build -o gomcbe-linux-x86 cmd/gomcbe/main.go
      env:
        GOOS: linux
        GOARCH: 386
    
    - name: Build for Windows (x64)
      run: go build -o gomcbe-windows-x64.exe cmd/gomcbe/main.go
      env:
        GOOS: windows
        GOARCH: amd64
    
    - name: Build for Windows (x86)
      run: go build -o gomcbe-windows-x86.exe cmd/gomcbe/main.go
      env:
        GOOS: windows
        GOARCH: 386
    
    - name: Build for ARM
      run: go build -o gomcbe-linux-arm cmd/gomcbe/main.go
      env:
        GOOS: linux
        GOARCH: arm
    
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gomcbe-binaries
        path: |
          gomcbe-linux-x64
          gomcbe-linux-x86
          gomcbe-windows-x64.exe
          gomcbe-windows-x86.exe
          gomcbe-linux-arm
